services:
  cf-warp-cli:
    build:
      context: .
    container_name: cf-warp-cli
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    restart: unless-stopped
    environment:
      WARP_CONNECTOR_TOKEN: "${WARP_CONNECTOR_TOKEN}"
      WARP_AUTOCONNECT: "true"
      WARP_MANAGE_FORWARD_CHAIN: "true"
      WARP_STATUS_INTERVAL_SECONDS: "${WARP_STATUS_INTERVAL_SECONDS:-15}"
    volumes:
      - ./data:/var/lib/cloudflare-warp
      - ./logs:/var/log/cloudflare-warp
